# ===== DEV STAGE =====
FROM node:18-alpine

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

WORKDIR /app

# Copy package files trước để cache layer
COPY package.json package-lock.json ./

RUN npm ci

# Copy source code
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
